### ISSUE TITLE
Naming conflict with Kong

### ISSUE THREAD

**Issue by christophelec** [quantmind/aio-kong#53]
The script for aio-kong (named kong) conflicts with the binary name for kong.

It's definitely not a show-stopper, but can be annoying when one has both a kong server and aio-kong locally, since using the kong command becomes undetermined.

Using a different script name would allow to have both at the same time without renaming manually or using absolute path.

**Comment by lsbardel** [comment]
sure, maybe we can name it `kongfig`

**Comment by christophelec** [comment]
```kongfig``` sounds good to me !

**Comment by lsbardel** [comment]
released in 0.8.0
